name: C++ CI with vSomeIP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake g++ libboost-all-dev git

    - name: Clone and build vSomeIP
      run: |
        git clone https://github.com/COVESA/vsomeip.git
        cd vsomeip
        mkdir build && cd build
        cmake ..
        make -j$(nproc)
        sudo make install

    - name: Set environment variables
      run: |
        echo "LD_LIBRARY_PATH=/usr/local/lib:\$LD_LIBRARY_PATH" >> $GITHUB_ENV

    - name: Configure CMake
      run: cmake .

    - name: Build
      run: cmake --build .

    - name: Run Tests
      run: ./test
